# Generated by Django 5.2.8 on 2025-12-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='profiles/default.jpeg', upload_to='profiles/'),
        ),
    ]
